name: CI dev

on:
  push:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: [self-hosted, docker]
    container:
      image: docker://fabernovel/android:api-29-v1.1.1

    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0

      - name: Ruby cache
        uses: actions/cache@v1.2.0
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Gradle cache
        uses: actions/cache@v1.2.0
        with:
          path: /root/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle check || bundle install

      - name: Fastlane
        env:
          AWS_S3_ACCESS_KEY: ${secrets.AWS_S3_ACCESS_KEY}
          AWS_S3_SECRET_KEY: ${secrets.AWS_S3_SECRET_KEY}
          COMMIT_HASH: ${GITHUB_SHA}
        run: bundle exec fastlane build_and_publish